# Generated by Django 2.0.7 on 2018-07-12 18:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a', models.CharField(max_length=30)),
                ('team_b', models.CharField(max_length=30)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('match_date', models.DateField()),
                ('results', models.CharField(max_length=5)),
                ('team_a_win', models.BooleanField(default=False)),
                ('team_b_win', models.BooleanField(default=False)),
                ('score_draw', models.BooleanField(default=False)),
                ('nil_draw', models.BooleanField(default=False)),
                ('other', django.contrib.postgres.fields.jsonb.JSONField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
