# Generated by Django 2.0.7 on 2018-07-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='location',
            field=models.CharField(max_length=30),
        ),
    ]
