# Generated by Django 2.0.7 on 2018-07-14 09:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_auto_20180714_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='other',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
