# Generated by Django 2.0.7 on 2018-07-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_auto_20180714_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b',
            field=models.CharField(max_length=50),
        ),
    ]
