# Generated by Django 2.0.7 on 2018-07-17 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_matchfile'),
    ]

    operations = [
    ]
