# Generated by Django 2.0.7 on 2018-07-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_auto_20180717_0733'),
    ]

    operations = [
    ]
