# Generated by Django 2.0.7 on 2018-07-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0007_auto_20180717_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='odds',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
