# Generated by Django 2.0.7 on 2018-07-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0009_auto_20180727_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='results',
            field=models.CharField(max_length=20),
        ),
    ]
