# Generated by Django 2.0.7 on 2018-08-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0010_auto_20180728_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='both_to_score_odds',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='double_chance_odds',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='over_under_25_odds',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='three_way_odds',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
