version: '3'
services:
  game_app:
    build: .
    ports:
     - "8081:8081"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - game_db
    links:
      - game_db
    environment:
      - DJANGO_SETTINGS_MODULE=conf.development
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=johnmilimowanjala@gmail.com
      - ADMIN_PASSWORD=Jh76gVcPOi2W
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=game
      - DB_USER=game_user
      - DB_PASSWORD=game_pass
      - DB_HOST=game_db
      - DB_PORT=5432

  game_db:
    image: postgres:9.5
    restart: always
    environment:
      - POSTGRES_DB=game
      - POSTGRES_PASSWORD=game_pass
      - POSTGRES_USER=game_user

#  redis:
#    image: "redis:alpine"