version: '3'
services:
  app:
    build: .
    ports:
     - "8081:8081"
    volumes:
      - ./:/usr/src/app
    environment:
      - DJANGO_SETTINGS_MODULE=conf.development
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=johnmilimowanjala@gmail.com
      - ADMIN_PASSWORD=Jh76gVcPOi2W

#  redis:
#    image: "redis:alpine"